[versions]
kotlin = "1.9.22"
androidx-core = "1.13.1"
lifecycle = "2.7.0"
compose = "1.6.7"
material3 = "1.2.1"
room = "2.6.1"
firebase_bom = "33.3.0"
firebase_auth = "23.0.0"
firebase_firestore = "25.1.0"
okhttp = "4.12.0"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase_bom" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebase_auth" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version.ref = "firebase_firestore" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }